disallowed-types = [
    { path = "std::collections::HashSet", reason = "prefer faster set", replacement = "hashbrown::HashSet" },
    { path = "std::collections::HashMap", reason = "prefer faster map", replacement = "hashbrown::HashMap" },
]
