[graph]
all-features = true
no-default-features = false

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]
confidence-threshold = 0.95

exceptions = [
    { allow = ["Zlib"], crate = "foldhash" },
    { allow = ["Unicode-3.0"], crate = "unicode-ident" },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
skip-tree = [
    { crate = "windows-sys", depth = 3 },
]

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0436", reason = "fixed upstream, waiting for 0.30 release: https://github.com/ratatui/ratatui/pull/1713" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
