name: Periodic Security audit
on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  security_audit:
    permissions:
      issues: write
      checks: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
