name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: read

    name: Rust Build
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
      SQLX_OFFLINE: true

    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: cargo build --verbose

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: cargo test --verbose

  spaces-check:
    permissions:
      contents: read

    name: Spaces Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Spaces check
        run: git diff-tree --check $(git hash-object -t tree /dev/null) HEAD

  spellings:
    permissions:
      contents: read

    name: Codespell
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install codespell
        run: sudo apt-get install -y codespell

      - name: Run codespell
        run: codespell -L ratatui,crate src/ README.md
